version: '3.8'
services:
  event-store-db-pg:
    image: postgres:latest
    environment:
      - POSTGRES_DB=facebluk
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - '5433:5432'
    volumes:
      - ./docker-data/event-store-db-pg:/var/lib/postgresql/data

  msg-broker-rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - '5672:5672'
      - '15672:15672'
